---
- name: Prompt for user input
  hosts: webservers
  vars_prompt:
    - name: user_name
      prompt: Enter username
      private: no
    - name: password
      prompt: Enter password
      private: yes
  tasks:
    - debug:
        msg: "The username is {{ user_name }} and password is {{ password }}."
...